### ISSUE TITLE
Progress for this week + this week activity

### ISSUE THREAD

**Issue by Sophia-Villamayor** [Sophia-Villamayor/saas-website#1]
@muxlowc
Hi Christina, I apologize for continuously tagging you really late.
Here is my progress for this assignment, however, I just have a couple of concerns:
-I'm not too sure on how to make my navigation on the right side
-Also, regards to the header, when I change different screen sizes, I have to use position relative + absolute, is this okay? 
-When I go to the smallest screen size, I have a hard time on getting the banner to become a black background instead of having the image, is that possible? If not, it's okay :)

I feel a little discouraged regards to my homepage, I understand all of the course material, and I feel as if I excelled from last semester. However, I just feel really stuck in terms of keeping my homepage proportionate and having it look professional. 

So sorry for bothering!!! Here is my screen shot as well

<img width="1121" alt="Screen Shot 2020-04-15 at 10 34 55 PM" src="https://user-images.githubusercontent.com/54897840/79412417-7048b080-7f73-11ea-89f0-f2919c6c74f7.png">

**Comment by muxlowc** [comment]
@Sophia-Villamayor 

1) you can try adding "text-align: right" on your nav?
2) absolutely! if adding those classes is doing what you want them to, you can definitely use it :)
3) you can add a class to your image and add display: none, on the mobile size/ at query 38em (or whatever size you want), add display: block;, sothat your image doesnt appear on mobile.. and then on your banner just add a background-color of black. Hopefully i understood your question correctly!

Don't get discouraged! I still get frustrated with code all the time haha. You still have a week before hand-in, so sometimes walking away for a day and coming back helps alot! :)

**Comment by Sophia-Villamayor** [comment]
@muxlowc Thank you so much!!!!!!
